name: Sorbet
on: # yamllint disable-line rule:truthy
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sorbet:
    name: Sorbet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: ruby/setup-ruby@52753b7da854d5c07df37391a986c76ab4615999 # v1.191.0
        with:
          bundler-cache: true

      - run: bundle exec tapioca gem --verify

      - run: bundle exec srb tc

      - run: bundle exec spoom srb coverage

      - run: |
          bundle exec spoom srb bump --from=false --to=true --dry
          bundle exec spoom srb bump --from=true --to=strict --dry
          bundle exec spoom srb bump --from=strict --to=strong --dry

      - run: bundle exec spoom srb coverage snapshot --save

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: spoom_data
          path: ./spoom_data/

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ./script/generate-coverage-report
        env:
          GH_TOKEN: ${{ github.token }}

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: spoom_report
          path: ./spoom_report.html
